import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"  className={openSans.className}>
      <body className="max-w-screen-2xl mx-auto">
        <Header />
        <main className="min-h-screen text-black">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
